version: '3'
services:
  web:
    build: .
    command: yarn run start
    deploy:
      replicas: 3

  lb:
    image: dockercloud/haproxy
    ports:
      - 4000:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # stores the main data for the project, user, site, instance etc.
  postgres-core:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma1
      POSTGRES_PASSWORD: prisma1
    volumes:
      - core-data:/var/lib/postgresql/data
  
  # stores the raw binary data that prisma1 still cannot handle
  postgres-content:
    image: postgres
    ports: 
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma2
      POSTGRES_PASSWORD: prisma2
    volumes:
      - content-data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  # the prisma 1 servers
  prisma1-manager:
    image: prismagraphql/prisma-prod:1.34
    depends_on: 
      - rabbitmq
    ports:
    - "4467:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        rabbitUri: amqp://prisma1:prisma1@rabbitmq:5672
        enableManagementApi: true
        databases:
          mydb:
            connector: postgres
            host: postgres-core
            user: prisma1
            password: prisma1
            rawAccess: true
            port: 5432
            migrations: true
  prisma1-worker:
    image: prismagraphql/prisma-prod:1.34
    deploy:
      replicas: 3
    depends_on: 
      - rabbitmq
    environment:
      PRISMA_CONFIG: |
        port: 4466
        rabbitUri: amqp://prisma1:prisma1@rabbitmq:5672
        enableManagementApi: false
        databases:
          mydb:
            connector: postgres
            host: postgres-core
            user: prisma1
            password: prisma1
            rawAccess: true
            port: 5432
            migrations: true
  prisma:
    image: nginx
    ports:
      - "4466:4466"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=prisma1
      - RABBITMQ_PASSWORD=prisma1
      - RABBITMQ_NODE_PORT_NUMBER=5672
    volumes:
      - 'rabbitmqstats_data:/bitnami'

volumes:
  core-data:
  content-data:
  rabbitmqstats_data: